credentials:
  usernames:
    sshah:
      email: email@gmail.com
      logged_in: False # Will be managed automatically
      name: Shashvat
      password: password # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name

